spring:
  application:
    name: collaboration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/collaboration
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  sql:
    init:
      mode: always

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs