INSERT INTO users (id, nickname) VALUES (1, '홍길동');
INSERT INTO products (id, brand_name, thumbnail_image_url, name, review_score, recent_review_score, review_count, original_price, sale_price, member_price, discount_rate, coupon_available, coupon_dday, unit_price, unit_quantity, unit, free_delivery, arrival_date, deadline_at, max_point) VALUES (10023, '떡이야', 'https://example.com/images/item/10023.jpg', '생크림 과일 모찌 참쌀 떡 딸기 모찌', 4.7, 4.8, 1230, 15900, 11780, 10900, 25, false, null, null, null, null, true, '2026-05-13', null, 589);
INSERT INTO products (id, brand_name, thumbnail_image_url, name, review_score, recent_review_score, review_count, original_price, sale_price, member_price, discount_rate, coupon_available, coupon_dday, unit_price, unit_quantity, unit, free_delivery, arrival_date, deadline_at, max_point) VALUES (10024, '넵담', 'https://example.com/images/item/10024.jpg', '넵담 두바이 쭌득 쿠키 4개 두쭌쿠 카다이프', 4.9, 4.9, 854, 42700, 23460, 21000, 45, false, null, null, null, null, true, '2026-05-13', null, 1173);
INSERT INTO products (id, brand_name, thumbnail_image_url, name, review_score, recent_review_score, review_count, original_price, sale_price, member_price, discount_rate, coupon_available, coupon_dday, unit_price, unit_quantity, unit, free_delivery, arrival_date, deadline_at, max_point) VALUES (10025, '오뚜기', 'https://example.com/images/item/10025.jpg', '오뚜기 참쌀 숙 호떡 믹스 300G 5개', 4.5, 4.6, 3201, 24300, 22900, 21000, 8, false, null, null, null, null, true, '2026-05-13', null, 1145);
INSERT INTO recommendation_sections (id, user_id) VALUES (1, 1);
INSERT INTO recommendation_products (id, recommendation_section_id, product_id, display_order) VALUES (1, 1, 10023, 1);
INSERT INTO recommendation_products (id, recommendation_section_id, product_id, display_order) VALUES (2, 1, 10024, 2);
INSERT INTO recommendation_products (id, recommendation_section_id, product_id, display_order) VALUES (3, 1, 10025, 3);
INSERT INTO orders (id, available_amount, available_point, available_money, hidden_point, all_use_amount) VALUES (1, 87, 80, 0, 7, 87);
INSERT INTO pending_points (id, order_id, total_point, purchase_total_point, basic_point, npay_money_point, review_point, membership_point) VALUES (1, 1, 1472, 722, 289, 433, 750, 1156);
INSERT INTO card_benefits (id, product_id, title) VALUES (1, 10023, '라이프플랜 카드 최대 374원 추가 적립(2%)');
INSERT INTO card_benefits (id, product_id, title) VALUES (2, 10023, '최대 12개월 무이자 할부 · 60개월 특별금리');
INSERT INTO card_benefits (id, product_id, title) VALUES (3, 10024, '라이프플랜 카드 최대 374원 추가 적립(2%)');
INSERT INTO card_benefits (id, product_id, title) VALUES (4, 10024, '최대 12개월 무이자 할부 · 60개월 특별금리');
INSERT INTO card_benefits (id, product_id, title) VALUES (5, 10025, '라이프플랜 카드 최대 374원 추가 적립(2%)');
INSERT INTO card_benefits (id, product_id, title) VALUES (6, 10025, '최대 12개월 무이자 할부 · 60개월 특별금리');